# Rstudio
#
# # Charles Peterson <cpeterson@oarc.ucla.edu>
# Rstudio/R container for Hoffman2
# Built with oneAPI/MKL
# # Created 8/2023
FROM docker.io/rockylinux:9.2
RUN dnf update -y ; dnf install epel-release -y ; dnf install -y pkg-config zlib openssl wget make git vim less hdf5 gcc gfortran g++ ca-certificates  cmake ant readline readline-devel  libX11-devel libXt-devel zlib-devel bzip2-devel xz-devel pcre2-devel curl-devel

RUN echo "[oneAPI]" > /tmp/oneAPI.repo && \
    echo "name=Intel® oneAPI repository" >> /tmp/oneAPI.repo && \
    echo "baseurl=https://yum.repos.intel.com/oneapi" >> /tmp/oneAPI.repo && \
    echo "enabled=1" >> /tmp/oneAPI.repo && \
    echo "gpgcheck=1" >> /tmp/oneAPI.repo && \
    echo "repo_gpgcheck=1" >> /tmp/oneAPI.repo && \
    echo "gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB" >> /tmp/oneAPI.repo && \
    mv /tmp/oneAPI.repo /etc/yum.repos.d/ && \
    dnf install -y intel-basekit intel-hpckit

ENV R_VERSION=4.3.2
ENV MKL_INTERFACE_LAYER=GNU,LP64 
ENV MKL_THREADING_LAYER=GNU
ENV CFLAGS="-O3  -m64 -fPIC -I\${MKLROOT}/include"
ENV FCFLAGS="-m64 -O3 -fPIC -I\${MKLROOT}/include"
ENV BLAS_LIBS="-L\${MKLROOT}/lib/intel64 -lmkl_rt"
ENV LAPACK_LIBS="-L\${MKLROOT}/lib/intel64 -lmkl_rt"
RUN bash -c "source /opt/intel/oneapi/setvars.sh \
     && curl -O https://cran.rstudio.com/src/base/R-4/R-${R_VERSION}.tar.gz \
     && tar -xzvf R-${R_VERSION}.tar.gz \
     &&  cd R-${R_VERSION}  \
     && CXX11=g++ CXX14=g++ CXX17=g++ CXX20=g++ CXX=g++ CC=gcc FC=gfortran ./configure  \ 
        --with-blas='-L${MKLROOT}/lib/intel64 -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl' \
       --enable-R-shlib --with-lapack  --enable-threads=posix --enable-memory-profiling \
     && make ; make install "
       

RUN wget https://download2.rstudio.org/server/rhel9/x86_64/rstudio-server-rhel-2023.09.1-494-x86_64.rpm \
    && yum install -y rstudio-server-rhel-2023.09.1-494-x86_64.rpm \ 
    && ln -fs /usr/lib/rstudio-server/bin/rstudio-server /usr/local/bin \
    && ln -fs /usr/lib/rstudio-server/bin/rserver /usr/local/bin \
    && mkdir -p /etc/R


ENV export R_BIN=$(which R)
RUN echo "rsession-which-r=${R_BIN}" >/etc/rstudio/rserver.conf

RUN echo "[*]\nlog-level=warn\nlogger-type=syslog" > /etc/rstudio/logging.conf

ENV R_VER="4.3.2"
RUN echo "r-libs-user=~/R/APPTAINER/h2-rstudio_4.3.2" > /etc/rstudio/rsession.conf
RUN mkdir -pv /apps/rstudio
COPY ./rstudio-startup.sh /apps/rstudio/rstudio-startup.sh
RUN chmod 755 /apps/rstudio/rstudio-startup.sh
ENTRYPOINT bash -c " source /opt/intel/oneapi/setvars.sh --force ; /apps/rstudio/rstudio-startup.sh"
#
