# Rstudio
#
# # Charles Peterson <charliecpeterson@gmail.com>
# # Created 2/2022
FROM docker.io/ubuntu:22.04
RUN apt update ; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends pkg-config zlib1g-dev openssl libssl-dev wget make git vim less libxt6 libhdf5-dev

RUN apt update ; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
   bzip2 \
   ca-certificates  \
   wget make python3 python3-dev \
   gcc \
   automake \
   autopoint \
   appstream \
   build-essential \
   cmake \
   git \
   libass-dev \
   libbz2-dev \
   libfontconfig1-dev \
   libfreetype6-dev \
   libfribidi-dev \
   libharfbuzz-dev \
   libjansson-dev \
   liblzma-dev \
   libmp3lame-dev \
   libnuma-dev \
   libogg-dev \
   libopus-dev \
   libsamplerate-dev \
   libspeex-dev \
   libtheora-dev \
   libtool \
   libtool-bin \
   libturbojpeg0-dev \
   libvorbis-dev \
   libx264-dev \
   libxml2-dev \
   libvpx-dev \
   m4 \
   make \
   meson \
   nasm \
   ninja-build \
   patch \
   pkg-config \
   tar \
   zlib1g-dev

RUN wget https://github.com/HandBrake/HandBrake/releases/download/1.5.1/HandBrake-1.5.1-source.tar.bz2 ; tar -vxf HandBrake-1.5.1-source.tar.bz2 

RUN cd HandBrake-1.5.1 ; ./configure  --disable-gtk ; cd build \
    && make ; make install \
    && cd ../.. ; rm -rf HandBrake-1.5.1*

 
