#
FROM oarcrtg/h2-build:ubuntu20.04-gcc10.3.0-oneapi2022.1.2 as build
RUN apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget liblzma-dev libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev \
    && wget https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tgz \
    && tar -vxf Python-3.9.10.tgz ; rm Python-3.9.10.tgz  \
    && cd Python-3.9.10 ; ./configure --enable-shared --prefix=/apps/python \
    && make ; make install \
    && cd ../ ; rm -r Python-3.9.10
ENV LD_LIBRARY_PATH=/apps/python/lib:$LD_LIBRARY_PATH
ENV PATH=/apps/python/bin:$PATH
COPY ./lammps-cmake /lammps-cmake
RUN apt update ; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends  gcc-multilib pkg-config zlib1g-dev openssl libssl-dev wget make git \
  && wget https://github.com/lammps/lammps/archive/refs/tags/stable_29Sep2021_update2.tar.gz \
  && tar -vxf stable_29Sep2021_update2.tar.gz ; rm stable_29Sep2021_update2.tar.gz \
  && cd lammps-stable_29Sep2021_update2 ; mkdir build ; cd build \
  && mv /lammps-cmake  ../cmake/presets/intel.cmake \
  && cmake -C ../cmake/presets/intel.cmake -D BUILD_MPI=yes -D BUILD_OMP=yes -D LAMMPS_MACHINE=mpi -DCMAKE_CXX_COMPILER=icpc -DCMAKE_C_COMPILER=icc -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_INSTALL_PREFIX=/apps/lammps ../cmake \
  && make ; make install \
  && cd ../.. ; rm -rf lammps-stable_29Sep2021_update2

FROM oarcrtg/h2-run:ubuntu20.04-gcc10.3.0-oneapi2022.1.2
RUN apt update ; apt-get install -y --no-install-recommends libpng16-16 zlib1g  \
    && rm -rf /var/lib/apt/lists/*  
COPY --from=build /apps/ /apps/
ENV LD_LIBRARY_PATH=/apps/python/lib:/apps/lammps/lib:$LD_LIBRARY_PATH
ENV PATH=/apps/python/bin:/apps/lammps/bin:$PATH
