# Rstudio
#
# # Charles Peterson <cpeterson@oarc.ucla.edu>
# # Created 4/2023
FROM docker.io/rocker/rstudio:4.4.0
RUN apt update ; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends pkg-config zlib1g-dev openssl libssl-dev wget make git vim less libxt6 libhdf5-dev libudunits2-dev

RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y \
        curl iproute2 bc libxml2 libxml2-dev libglpk-dev \
        libv8-dev jags libcairo2-dev libbz2-dev liblzma-dev \
        libmagick++-dev \
        tcl-dev tk-dev \
        libgdal-dev libproj-dev libicu-dev libgsl-dev \
        fontconfig libfreetype6-dev libxml2-dev libproj-dev libgsl-dev bc \
                    libfontconfig1-dev pkg-config libharfbuzz-dev libfribidi-dev \
                   webp-pixbuf-loader zstd libzstd-dev libwebp-dev \
                     libglpk-dev fftw3-dev patch libhdf5-serial-dev \
                       libnlopt-dev cmake make \
    && rm -rf /var/lib/apt/lists/*


ENV R_VER="4.4.0"
RUN echo "r-libs-user=~/R/APPTAINER/h2-rstudio_4.4.0" > /etc/rstudio/rsession.conf
RUN mkdir -pv /apps/rstudio
COPY ./rstudio-startup.sh /apps/rstudio/rstudio-startup.sh
RUN chmod 755 /apps/rstudio/rstudio-startup.sh
ENTRYPOINT /apps/rstudio/rstudio-startup.sh

