# Dockerfile for BEDOPS build for Hoffman2
# Charles Peterson <cpeterson@oarc.ucla.edu>
# Created 11/2022
#
# This increasing the TOKENS MAX LENGTH as suggested in 
# https://www.biostars.org/p/283321/
#
#
FROM docker.io/ubuntu:22.04

RUN apt update ; apt-get install -y --no-install-recommends  \
                libcurl4-openssl-dev libncurses5-dev libncursesw5-dev liblzma-dev zlib1g-dev autoconf git gcc g++ libc6-dev make ca-certificates bzip2 libbz2-dev

RUN git clone https://github.com/bedops/bedops \
    && cd bedops \
    && git checkout v2.4.41 \
    && sed -i 's/REST_EXPONENT 15/REST_EXPONENT 18/g' ./interfaces/general-headers/suite/BEDOPS.Constants.hpp \
    && sed -i 's/define TOKENS_MAX_LENGTH INT_TOKENS_MAX_LENGTH/define TOKENS_MAX_LENGTH (100*INT_TOKENS_MAX_LENGTH)/g' ./interfaces/general-headers/suite/BEDOPS.Constants.hpp \
    && make all ; make install_all \
    && cp bin/* /usr/local/bin \
    && cd .. ; rm -rf bedops

RUN git clone https://github.com/samtools/htslib \
    && cd htslib \
    && git checkout 1.16 \
    && git submodule update --init --recursive \
    && autoreconf -i \
    && make ; make install \
    && cd .. ; rm -rf htslib

RUN git clone https://github.com/samtools/samtools \
    && cd samtools \
    && git checkout 1.16.1 \
    && autoconf -Wno-syntax \
    && ./configure \
    && make ; make install \
    && cd .. ; rm -rf samtools


