# Rstudio
#
# # Charles Peterson <charliecpeterson@gmail.com>
# # Created 2/2022
FROM docker.io/rocker/rstudio:4.1.0
RUN apt update ; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends pkg-config zlib1g-dev openssl libssl-dev wget make git vim less libxt6 libhdf5-dev

RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y \
        curl iproute2 bc libxml2 libxml2-dev libglpk-dev \
        libv8-dev jags libcairo2-dev libbz2-dev liblzma-dev \
        libmagick++-dev \
        tcl-dev tk-dev \
        libgsl-dev \
        libudunits2-dev \
    && rm -rf /var/lib/apt/lists/*

ENV R_VER="4.1.0"
RUN echo "r-libs-user=~/R/APPTAINER/h2-rstudio_4.1.0" > /etc/rstudio/rsession.conf
RUN mkdir -pv /apps/rstudio
COPY ./rstudio-startup.sh /apps/rstudio/rstudio-startup.sh
RUN chmod 755 /apps/rstudio/rstudio-startup.sh
ENTRYPOINT /apps/rstudio/rstudio-startup.sh

