# OpenSees
# https://opensees.berkeley.edu/
# OpenSeesMP and OpenSeespy
# # Charles Peterson <cpeterson@oarc.ucla.edu>
# # Created 2/2022
FROM oarcrtg/h2-build:ubuntu20.04-gcc10.3.0-oneapi2022.1.2 as build
RUN apt update ; apt-get install -y --no-install-recommends gcc-multilib pkg-config zlib1g-dev openssl libssl-dev wget make git 

ENV PATH=/apps/python/bin:$PATH
ENV LD_LIBRARY_PATH=/apps/python/lib:$LD_LIBRARY_PATH

RUN apt-get update  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    liblzma-dev  libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev \
    && wget https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tgz \
    && tar -vxf Python-3.9.10.tgz ; rm Python-3.9.10.tgz  \
    && cd Python-3.9.10 ; ./configure --prefix=/apps/python \
    && make ; make install \
    && cd ../ ; rm -r Python-3.9.10 \
    && pip3 install openseespy

COPY ./openseesmp-makescotch /tmp/openseesmp-makescotch
RUN cd /tmp ; wget https://gforge.inria.fr/frs/download.php/file/37622/scotch_6.0.6.tar.gz \
   && tar -vxf scotch_6.0.6.tar.gz \
   && cd scotch_6.0.6/src ; mkdir -p /apps/scotch \
   && mv /tmp/openseesmp-makescotch ./Makefile.inc \
   && sed -i 's/\/usr\/local/\/apps\/scotch/g' Makefile \
   && make ptesmumps ; make install  \
   && cd /tmp ; rm -rf scotch* 

RUN cd /tmp ; wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz \
    && tar -vxf parmetis-4.0.3.tar.gz \
    && cd parmetis-4.0.3 \
    && make config openmp=-qopenmp cc=mpiicc cxx=mpiicpc prefix=/apps/parmetis \
    && make ; make install \ 
    && cd metis ; mkdir -pv /apps/metis \
    && make config openmp=-qopenmp cc=mpiicc prefix=/apps/metis \
    && make ; make install \
    && cd /tmp ;rm -rf parmetis*

COPY ./openseesmp-makemumps /tmp/openseesmp-makemumps
RUN cd /tmp ; wget http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz \
  && tar -vxf MUMPS_5.0.2.tar.gz ; cd MUMPS_5.0.2  \
  && mv /tmp/openseesmp-makemumps ./Makefile.inc \
  && cd /tmp/MUMPS_5.0.2 ; make \
  && mkdir -pv /apps/mumps \
  && cp -r lib /apps/mumps \
  && cp -r include /apps/mumps \
  && cd /tmp ; rm -rf MUMPS*  

COPY ./openseesmp-makeopenseesmp /tmp/openseesmp-makeopenseesmp
RUN cd /tmp ; git clone https://github.com/OpenSees/OpenSees \
    && cd OpenSees ; git checkout v3.0.0 \
    && mkdir -pv /tmp/OpenSees/lib \
    && mkdir -pv /tmp/OpenSees/bin \
    && mkdir -pv /apps/OpenSees \
    && mv /tmp/openseesmp-makeopenseesmp ./Makefile.def \
    && make \
    && cp -r bin /apps/OpenSees \
    && cp -r lib /apps/OpenSees \
    && cd /tmp ; rm -rf OpenSees* 
#
#FROM oarcrtg/h2-run:ubuntu20.04-gcc10.3.0-oneapi2022.1.2
#RUN apt update ; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends zlib1g libtcl8.6 \
#    && rm -rf /var/lib/apt/lists/*
#COPY --from=build /apps/  /apps/
#ENV PATH=/apps/OpenSees/bin:/apps/python/bin:$PATH
#ENV LD_LIBRARY_PATH=/apps/OpenSees/lib:/apps/python/lib:$LD_LIBRARY_PATH

